name: Deploy with Docker to AWS Server
# on => 실행 조건
on:
  push:
  # main으로 커밋 & 푸쉬를 날렸을 때
    branches:
      - main #main commit and push = [main,master]
jobs:
  deploy:
# Github Actions가 제공하는 우분투 환경에서 실행
   # AWS EC2가 아닌 깃허브 액션스의 임시로 사용하는 우분투
    runs-on: ubuntu-latest

    # 실행 순서 지정
    # name = stage = step 
    steps:
     #코드 체크 (Repository를 체크 => 소스를 확인하는 단계 => 어떤 소스를 가져올지 => src/build.gradle .. 이런거 확인)
     - name: Checkout:repository
       uses: actions/checkout@v4
     #JDK 설정 => SpringBoot 버전을 확인 => jar 파일을 만들기 위해 jdk 설정
     - name: SetUp JDK 21
       uses: actions/setup-java@v4
       with:
         # temurin 가장 작은 버전 => 가장 최소 단위의 JDK => 이건 이클립스에 있음
         distribution: 'temurin'
         java-version: '21'
     # 환경설정 시작    
     # DB관련 파일을 .env 파일로
     - name: 환경설정
       run: |
           # 기존 파일 삭제
           rm -f .env
           # 새로운 .env 파일 생성
           touch .env
           echo "DB_URL=${{secrets.DB_URL}}" >> .env
           echo "DB_URL=${{secrets.DB_USERNAME}}" >> .env
           echo "DB_URL=${{secrets.DB_PASSWORD}}" >> .env
           
     # Gradlew 권한 부여 
     - name: Set gradlew permission
       run: |
         chmod +x ./gradlew
     # Gradle Build 
     - name: Build with Gradlew
       run: ./gradlew clean build -x test
       
     # docker Hub 연결 => 로그인 처리
     - name: Login DockerHub
       run: |
        echo "${{secrets.DOCKER_PASSWORD}}" |\
        docker login \
        -u "${{secrets.DOCKER_USERNAME}}" \
        --password-stdin
     # docker image 만들기
     - name: Build Docker Image
       run: |
        docker build \
         -t ${{secrets.DOCKER_USERNAME}}/last-app:latest
     # docker Hub로 올리기
     - name: Push Docker Image
       run: |
        docker push \
         ${{secrets.DOCKER_USERNAME}}/last-app:latest
         
     # AWS 연결 => 도커 허브 데이터를 pull
     - name: Set SSH key Permission
       run: |
         mkdir -p ~/.ssh
         echo "${{secrets.SERVER_SSH_KEY}}" > ~/.ssh/id_ed25519
         chmod 600 ~/.ssh/id_ed25519
     # ADD SSH Key 
     - name: Add SSH Key 
       uses: webfactory/ssh-agent@v0.5.3
       with:
         ssh-private-key: ${{secrets.SERVER_SSH_KEY}}
     # Add Known_hosts
     - name: Add Known_hosts
       run: |
         ssh-keyscan -H ed25519 43.201.105.73 >> ~/.ssh/known_hosts
    # Deploy on server DockerHub Image using
     - name: DockerHub Image using
       run: |
         ssh ubuntu@43.201.105.73 << 'EOF'
          docker stop last-app || true
          docker rm last-app || true
          docker pull ${{secrets.DOCKER_USERNAME}}/last-app:latest
          docker run -d --name last-app -p 9090:9090 ${{secrets.DOCKER_USERNAME}}/last-app:latest 
         EOF
    
   
